version: "3.6"
services:
  dev:
    build: .
    hostname: lua
    container_name: lua
    command: sleep infinity
    cap_add:
      - SYS_PTRACE
    volumes:
      - type: bind
        source: .
        target: /home/josiahp
